name: info-iv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - pytorch-cuda=12.1 
  - protobuf=3.20
  - lightning
  - hydra-core
  - matplotlib
  - glob2
  - ipykernel
  - seaborn
  - tensorboard
  - pip
  - pip:
      - torcheval
      - torchvision

