seed: 1
checkpoint_path: ""
expe_name: "uniform_nonlinear_iv/ols_cf"
expe_path: "logs/uniform_nonlinear/nce_gamma5/version_0"

type: "observed" # perform ols on "observed" or "latent" or "instrument"

dataset:
  path: 
  dimA: 6
  dimZ: 4
  dimX: 8
  dimY: 1
  alpha: 1 # Z = A @ M + alpha * V
  batch_size: 64
  n: 10000
  
  causal_effect: "nonlinear" # "linear" or "nonlinear"
  noise_distribution: "uniform" # "uniform" or "gaussian"
  gamma_train: 5
  gamma_test: 10
  
  hidden_dim: 16
  n_layers: 2

  shifts: [0,1,2,3,4,5,6,7,8,9] # shifts to apply to the data

  confounding_strength: 2 # scaling factor for the confounding effect

model:
  hidden_dim: 32
  num_layers: 3
  activation: "tanh"

optimizer:
  name: "adam" 
  scheduler: "plateau" 
  weight_decay: 0
  lr: 0.01

trainer:
  root_dir: "logs"
  devices: 1
  accelerator: "mps"
  max_epochs: 100

