seed: 6
checkpoint_path: ""
expe_name: "imca_linear/ivae/"

device: "cuda:1"
n_workers: 1

dataset:
  path: 
  dimA: 8
  dimZ: 6
  dimX: 12
  dimY: 1

  
  batch_size: 64
  n: 5000

  n_val: 1000
  
  causal_effect: "linear" # "linear" or "nonlinear"
  
  confounding_strength: 1.
  indep_latents: False

  # mixing parameters gO: Z -> X
  hidden_dim: 16
  n_layers: 2

  M0: 

model:
  hidden_dim: [16,32,64]
  num_layers: 3
  dropout_rate: 0.2

  activation: "xtanh"
  slope: 0.1

loss:
  kernel: "gaussian"
  a: 100
  b: 1
  c: 0
  d: 10

optimizer:
  name: "adam" #ToDo: 
  lr: 0.001
  scheduler: "plateau" # "cosine" or "step"
  weight_decay: 1e-5

trainer:
  root_dir: "logs"
  devices: 1
  max_epochs: 20